[package]
name = "jsonld"
version = "0.1.0"
description = "A JSON-LD Processor for Rust"
authors = ["ct0r <ct0r@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
lazy_static = "1.3.0"
serde_json = "1.0"
url = "2.0.0"