pub struct JsonLdError {
    pub code: JsonLdErrorCode,
    pub message: Option<String>,
}

pub enum JsonLdErrorCode {
    CollidingKeywords,
    ConflictingIndexes,
    CyclicIRIMapping,
    InvalidIdValue,
    InvalidIndexValue,
    InvalidNestvalue,
    InvalidPrefixValue,
    InvalidPropagateValue,
    InvalidReverseValue,
    InvalidImportValue,
    InvalidVersionValue,
    InvalidBaseIRI,
    InvalidContainerMapping,
    InvalidContextEntry,
    InvalidContextNullification,
    InvalidDefaultLanguage,
    InvalidIRIMapping,
    InvalidKeywordAlias,
    InvalidLanguageMapValue,
    InvalidLanguageMapping,
    InvalidLanguageTaggedString,
    InvalidLanguageTaggedValue,
    InvalidLocalContext,
    InvalidRemoteContext,
    InvalidReverseProperty,
    InvalidReversePropertyMap,
    InvalidReversePropertyValue,
    InvalidScopedContext,
    InvalidScriptElement,
    InvalidSetOrListObject,
    InvalidTermDefinition,
    InvalidTypeMapping,
    InvalidTypeValue,
    InvalidTypedValue,
    InvalidValueObject,
    InvalidValueObjectValue,
    InvalidVocabMapping,
    IRIConfusedWithPrefix,
    KeywordRedeFinition,
    LoadingDocumentFailed,
    LoadingRemoteContextFailed,
    MultipleContextLinkHeaders,
    ProcessingModeConflict,
    ProtectedTermRedefinition,
    ContextOverflow,
}
